##################################################################################################
# staff service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: staff-service
  labels:
    app: staff-service
    service: staff-service
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
  selector:
    app: staff-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tts-p1-staff-service
  labels:
    account: staff-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service
  labels:
    app: staff-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff-service
  template:
    metadata:
      labels:
        app: staff-service
    spec:
      serviceAccountName: tts-p1-staff-service
      containers:
      - name: tts-p1-staff-service
        image: docker.io/scottli/tts-p1-staff-service:latest
        # image: asia-east1-docker.pkg.dev/ticket-tracking-system/tts-p1/staff-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
##################################################################################################
# ticket service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
  labels:
    app: ticket-service
    service: ticket-service
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
  selector:
    app: ticket-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tts-p1-ticket-service
  labels:
    account: ticket-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  labels:
    app: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      serviceAccountName: tts-p1-ticket-service
      containers:
      - name: tts-p1-ticket-service
        image: docker.io/scottli/tts-p1-ticket-service:latest
        # image: asia-east1-docker.pkg.dev/ticket-tracking-system/tts-p1/ticket-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
##################################################################################################
# front-end
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: tts-p1-frontend
        image: docker.io/scottli/tts-p1-frontend:latest
        # image: asia-east1-docker.pkg.dev/ticket-tracking-system/tts-p1/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80